service: aws-serverless-java-sample

provider:
  name: aws
  runtime: java8
  region: ap-northeast-1
  memorySize: 128

package:
  artifact: target/hello-dev.jar

functions:
  getHello:
    handler: app.hello.Get
    events:
      - http:
          path: hello
          method: GET
  postHello:
    handler: app.hello.Post
    events:
      - http:
          path: hello
          method: POST
